# Generated by Django 2.2.12 on 2020-05-22 00:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('INACTIVE', 'Inactive'), ('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('PAST_DUE', 'Past_due'), ('UNPAID', 'Unpaid')], default='INACTIVE', max_length=9)),
                ('customer_id', models.CharField(default='', max_length=100)),
                ('subscription_id', models.CharField(default='', max_length=100)),
                ('cards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=list, size=None)),
                ('payment_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('default_payment_method', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
